services:
  bank-manager-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank-manager-api
    container_name: bank-manager-api
    restart: always
    ports:
      - "2000:8000"
    networks:
      - mongodb-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    restart: always
    environment: 
       MONGO_INITDB_ROOT_USERNAME: jumpogpo
       MONGO_INITDB_ROOT_PASSWORD: superadmin
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    networks:
      - mongodb-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 2020:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: jumpogpo
      ME_CONFIG_BASICAUTH_PASSWORD: superadmin
      ME_CONFIG_MONGODB_URL: mongodb://jumpogpo:superadmin@mongodb:27017/
    networks:
      - mongodb-network
    depends_on:
      - mongodb

volumes:
  db_data:
    name: mongodb-data
    driver: local
  db_config:
    name: mongodb-config
    driver: local

networks:
  mongodb-network:
    name: mongodb_default